# Render.com Deployment Configuration
# Deploy with: render blueprint launch

services:
  # Jules API Server
  - type: web
    name: a2a-jules
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python api/jules_server.py
    envVars:
      - key: A2A_JULES_HOST
        value: 0.0.0.0
      - key: A2A_JULES_PORT
        value: 5006
      - key: A2A_DB_TYPE
        value: postgresql
      - key: A2A_DATABASE_URL
        fromDatabase:
          name: a2a-db
          property: connectionString
      - key: A2A_SECRET_KEY
        generateValue: true
      - key: A2A_ENABLE_AUTH
        value: true
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_OWNER
        value: dvanosdol88
    healthCheckPath: /health

  # Dashboard Server
  - type: web
    name: a2a-dashboard
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python monitoring/dashboard_server.py
    envVars:
      - key: A2A_DASHBOARD_HOST
        value: 0.0.0.0
      - key: A2A_DASHBOARD_PORT
        value: 5003
      - key: A2A_JULES_API_URL
        value: https://a2a-jules.onrender.com
      - key: A2A_DB_TYPE
        value: postgresql
      - key: A2A_DATABASE_URL
        fromDatabase:
          name: a2a-db
          property: connectionString
    healthCheckPath: /health

  # FlowForge UI
  - type: web
    name: a2a-flowforge
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python ui/flowforge/server.py
    envVars:
      - key: A2A_JULES_API_URL
        value: https://a2a-jules.onrender.com

databases:
  - name: a2a-db
    plan: starter
    databaseName: a2a_production
    user: a2a_user