services:
  - type: web
    name: a2a-system-dashboard
    runtime: python
    rootDir: dashboard
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn a2a_monitor_cloud:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DEMO_MODE
        value: true
      - key: REDIS_URL
        sync: false
      - key: JULES_API_URL
        sync: false
      - key: AI_CONNECTOR_URL
        sync: false