# Render.com Deployment Configuration - Minimal Setup
# Deploy with: render blueprint launch

services:
  # Jules API Server - Core A2A Service (REQUIRED)
  - type: web
    name: a2a-jules
    env: python
    region: oregon
    plan: free  # Using free tier
    buildCommand: pip install -r requirements.txt
    startCommand: python api/jules_server.py
    envVars:
      - key: A2A_JULES_HOST
        value: 0.0.0.0
      - key: A2A_JULES_PORT
        value: 5006
      - key: A2A_DB_TYPE
        value: postgresql
      - key: A2A_DATABASE_URL
        fromDatabase:
          name: a2a-db
          property: connectionString
      - key: A2A_SECRET_KEY
        generateValue: true
      - key: A2A_ENABLE_AUTH
        value: false  # Simplified for now
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_OWNER
        value: dvanosdol88
    healthCheckPath: /health

databases:
  - name: a2a-db
    plan: free
    databaseName: a2a_production
    user: a2a_user